In [1]:
import bs4 as bs
import urllib.request
import csv

page = 1
alltitle = [['id', 'book_id', 'authors', 'title', 'average_rating', 'ratings_count']]

while page != 9:

    url = 'https://www.goodreads.com/list/show/567.Best_Chapter_Books_to_Read_Out_Loud?page=' + str(++page)

    grURL = urllib.request.urlopen(url)
    grHTML = grURL.read()
    grURL.close()

    soup = bs.BeautifulSoup(grHTML, 'html.parser')
    #grAllSpans = soup.find_all("span")
    spans = soup.find_all('a', title= True)
    for links in spans:
        alltitle.append(links['id'], links['book_id'], links['authors'], links['title'], links['average_rating'], links['ratings_count'])
                   
        myFile = open('books.csv', 'w')
        with myFile:
            writer = csv.writer(alltitle)
            writer.writerows(alltitle)
            
    if page == 9:
        break
    page += 1

In [2]:
books_data = pd.read_csv('books.csv')

books_data.head()

,id,book_id,authors,title,average_rating,ratings_count
0,1,2767052,Suzanne Collins,"The Hunger Games (The Hunger Games, #1)",4.34,4780653
1,2,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479
2,3,41865,Stephenie Meyer,"Twilight (Twilight, #1)",3.57,3866839
3,4,2657,Harper Lee,To Kill a Mockingbird,4.25,3198671
4,5,4671,F. Scott Fitzgerald,The Great Gatsby,3.89,2683664